require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe ReposController do

  def mock_repo(stubs={})
    @mock_repo ||= mock_model(Repo, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all repos as @repos" do
      Repo.stub(:all) { [mock_repo] }
      get :index
      assigns(:repos).should eq([mock_repo])
    end
  end

  describe "GET show" do
    it "assigns the requested repo as @repo" do
      Repo.stub(:find).with("37") { mock_repo }
      get :show, :id => "37"
      assigns(:repo).should be(mock_repo)
    end
  end

  describe "GET new" do
    it "assigns a new repo as @repo" do
      Repo.stub(:new) { mock_repo }
      get :new
      assigns(:repo).should be(mock_repo)
    end
  end

  describe "GET edit" do
    it "assigns the requested repo as @repo" do
      Repo.stub(:find).with("37") { mock_repo }
      get :edit, :id => "37"
      assigns(:repo).should be(mock_repo)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created repo as @repo" do
        Repo.stub(:new).with({'these' => 'params'}) { mock_repo(:save => true) }
        post :create, :repo => {'these' => 'params'}
        assigns(:repo).should be(mock_repo)
      end

      it "redirects to the created repo" do
        Repo.stub(:new) { mock_repo(:save => true) }
        post :create, :repo => {}
        response.should redirect_to(repo_url(mock_repo))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved repo as @repo" do
        Repo.stub(:new).with({'these' => 'params'}) { mock_repo(:save => false) }
        post :create, :repo => {'these' => 'params'}
        assigns(:repo).should be(mock_repo)
      end

      it "re-renders the 'new' template" do
        Repo.stub(:new) { mock_repo(:save => false) }
        post :create, :repo => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested repo" do
        Repo.stub(:find).with("37") { mock_repo }
        mock_repo.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :repo => {'these' => 'params'}
      end

      it "assigns the requested repo as @repo" do
        Repo.stub(:find) { mock_repo(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:repo).should be(mock_repo)
      end

      it "redirects to the repo" do
        Repo.stub(:find) { mock_repo(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(repo_url(mock_repo))
      end
    end

    describe "with invalid params" do
      it "assigns the repo as @repo" do
        Repo.stub(:find) { mock_repo(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:repo).should be(mock_repo)
      end

      it "re-renders the 'edit' template" do
        Repo.stub(:find) { mock_repo(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested repo" do
      Repo.stub(:find).with("37") { mock_repo }
      mock_repo.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the repos list" do
      Repo.stub(:find) { mock_repo }
      delete :destroy, :id => "1"
      response.should redirect_to(repos_url)
    end
  end

end
